language: perl

perl:
  - 5.24
  - 5.30

sudo: true

env:
  global:
    - PGHOST=127.0.0.1
  matrix:
    - PGVERSION=12
    - PGVERSION=11
    - PGVERSION=10
    - PGVERSION=9.6
    - PGVERSION=9.5
    - PGVERSION=9.4
    - PGVERSION=9.3

before_install:
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5
    postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - sudo apt-get update -qq
  - sudo apt-get install -y
    postgresql-${PGVERSION}
    postgresql-client-${PGVERSION}
    postgresql-${PGVERSION}-pgtap
    postgresql-server-dev-${PGVERSION}
    postgresql-server-dev-all
    postgresql-plperl-${PGVERSION}
    debhelper fakeroot
    libtap-parser-sourcehandler-pgtap-perl
  # Set PATH as postgresql-server-dev-all pretends version is 11
  - export PATH=/usr/lib/postgresql/${PGVERSION}/bin:${PATH}

script:
  - perl Makefile.PL
  - BUCARDO_LOG_ERROR_CONTEXT=1 PATH=$PATH:/usr/lib/postgresql/${PGVERSION}/bin make test

after_failure:
  - cat log.context
